[appendix]
== Conformance Class Abstract Test Suite (Normative)

[NOTE]
====
Ensure that there is a conformance class for each requirements class and a test for each requirement (identified by requirement name and number)
====

=== Conformance Class A

[requeriment,type="verification"]
====

[requirement,type="general",label="Test id"]
======
conf/service/profile/basic-wps
======

[recommendation,type="general",label="Test purpose"]
======
Verify that the server implements the Basic WPS conformance class.
======

[requirement,type="general",label="Test method"]
======
Verify that the server implements the Synchronous WPS and/or the Asynchronous WPS conformance class. Verify that the requests and responses to a supported operation are syntactically correct. Verify that the service supports the Synchronous WPS Conformance class, the Asynchronous WPS Conformance class or both. Verify that all process offerings implement the native process model. Verify the following list of conformance tests:

- Conformance test 1
- Conformance test 2
======

====