== Terms and definitions

////
Note that the initial notice about terms ("This document uses the terms defined in OGC Policy Directive 49...")
is inserted automatically by Metanorma using the agreed standardised language, and you should not enter it here.
////

=== administrative change

change that does not alter the conformance abstract tests for any requirements

NOTE: An administrative change includes typographical errors, changes in wording to improve clarity or consistency, and perfunctory changes such as changes in version numbers.

=== critical Change

change that alters requirements in a way that is known to cause reverse compatibility issues

=== substantive change

change that alters requirements in a way that is not deemed to have a high risk for causing reverse compatibility issues


=== example term

term used for exemplary purposes

[.source]
<<ISO19101-1>>

NOTE: An example note.

[example]
Here's an example of an example term.

////
// List any abbreviations and their full expansions that are used in this document, if any.
=== Abbreviations

EX:: Example
////
