name: docker

on:
  push:
    branches: [ master, main ]
  pull_request:
    paths-ignore:
      - .github/workflows/test.yml
      - .github/workflows/pages.yml
  repository_dispatch:
    types: [ metanorma/metanorma-docker ]

jobs:
  generate:
    name: Test on docker://metanorma/mn
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: /config/fonts
          key: fontist-docker
          restore-keys: fontist-docker

      - uses: actions/cache@v2
        with:
          path: ~/.metanorma-ietf-workgroup-cache.json
          key: metanorma-ietf-workgroup-cache
          restore-keys: metanorma-ietf-workgroup-cache

      - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@master
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - name: Test individual templates
        shell: bash
        run: |
          source doctypes.env
          for template in $DOCTYPES
          do
            metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite
            if [ -f test/${template}/document.adoc ]
            then
              metanorma compile --no-install-fonts test/${template}/document.adoc
            else
              for docfile in test/${template}/*.adoc
              do
                metanorma compile --no-install-fonts $docfile
              done
            fi
          done
